#!/usr/bin/python

import sys
from PyQt4 import QtGui, QtCore
import rh.prototype.shotgungrab
import rh.ui.palette

def main():
    app = QtGui.QApplication(sys.argv)
    rh.ui.palette.setDarkPalette()
    #app.processEvents()
    shotgun = rh.prototype.shotgungrab.RHShotgun()
    sys.exit(app.exec_())

if __name__ == '__main__':
    main()